-- Phase 12E: Weekly intelligence briefs (generated by scripts/generate_weekly_brief.ts).

create table public.weekly_briefs (
  id uuid primary key default gen_random_uuid(),
  week_ending date not null,
  brief_json jsonb not null,
  generated_at timestamptz not null default now(),
  constraint weekly_briefs_week_ending_unique unique (week_ending)
);

comment on table public.weekly_briefs is 'Weekly intelligence briefs: headline events, regional analysis, humanitarian alerts, emerging risks.';
comment on column public.weekly_briefs.week_ending is 'End date of the 7-day window (e.g. Sunday or as-of date).';
comment on column public.weekly_briefs.brief_json is 'Structured brief: headline_events, regional_analysis, humanitarian_alerts, emerging_risks.';

create index idx_weekly_briefs_week_ending_desc on public.weekly_briefs (week_ending desc);

alter table public.weekly_briefs enable row level security;

create policy weekly_briefs_select_all on public.weekly_briefs
  for select using (true);

create policy weekly_briefs_insert_system on public.weekly_briefs
  for insert with check (true);

create policy weekly_briefs_update_system on public.weekly_briefs
  for update using (true);
